-- Seed movies data
INSERT INTO public.movies (title, year, director, plot, poster_url, backdrop_url, runtime, genres, actors) VALUES
('The Shawshank Redemption', 1994, 'Frank Darabont', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg', 'https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg', 142, ARRAY['Drama'], ARRAY['Tim Robbins', 'Morgan Freeman', 'Bob Gunton']),

('The Godfather', 1972, 'Francis Ford Coppola', 'The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant youngest son.', 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', 'https://image.tmdb.org/t/p/original/tmU7GeKVybMWFButWEGl2M4GeiP.jpg', 175, ARRAY['Crime', 'Drama'], ARRAY['Marlon Brando', 'Al Pacino', 'James Caan']),

('The Dark Knight', 2008, 'Christopher Nolan', 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.', 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg', 'https://image.tmdb.org/t/p/original/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg', 152, ARRAY['Action', 'Crime', 'Drama'], ARRAY['Christian Bale', 'Heath Ledger', 'Aaron Eckhart']),

('Pulp Fiction', 1994, 'Quentin Tarantino', 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg', 'https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg', 154, ARRAY['Crime', 'Drama'], ARRAY['John Travolta', 'Uma Thurman', 'Samuel L. Jackson']),

('Inception', 2010, 'Christopher Nolan', 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.', 'https://image.tmdb.org/t/p/w500/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg', 'https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg', 148, ARRAY['Action', 'Sci-Fi', 'Thriller'], ARRAY['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page']),

('Forrest Gump', 1994, 'Robert Zemeckis', 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.', 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg', 'https://image.tmdb.org/t/p/original/qdIMHd4sEfJSckfVJfKQvisL02a.jpg', 142, ARRAY['Drama', 'Romance'], ARRAY['Tom Hanks', 'Robin Wright', 'Gary Sinise']),

('The Matrix', 1999, 'Lana Wachowski', 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.', 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg', 'https://image.tmdb.org/t/p/original/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg', 136, ARRAY['Action', 'Sci-Fi'], ARRAY['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss']),

('Goodfellas', 1990, 'Martin Scorsese', 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito.', 'https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg', 'https://image.tmdb.org/t/p/original/sw7mordbZxgITU877yTpZCud90M.jpg', 145, ARRAY['Crime', 'Drama'], ARRAY['Robert De Niro', 'Ray Liotta', 'Joe Pesci']),

('Interstellar', 2014, 'Christopher Nolan', 'A team of explorers travel through a wormhole in space in an attempt to ensure humanitys survival.', 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', 'https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg', 169, ARRAY['Adventure', 'Drama', 'Sci-Fi'], ARRAY['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain']),

('Parasite', 2019, 'Bong Joon-ho', 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.', 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg', 'https://image.tmdb.org/t/p/original/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg', 132, ARRAY['Comedy', 'Drama', 'Thriller'], ARRAY['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong']),

('The Lord of the Rings: The Fellowship of the Ring', 2001, 'Peter Jackson', 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.', 'https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg', 'https://image.tmdb.org/t/p/original/x2RS3uTcsJJ9IfjNPcgDmukoEcQ.jpg', 178, ARRAY['Action', 'Adventure', 'Drama'], ARRAY['Elijah Wood', 'Ian McKellen', 'Orlando Bloom']),

('Fight Club', 1999, 'David Fincher', 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.', 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg', 'https://image.tmdb.org/t/p/original/hZkgoQYus5vegHoetLkCJzb17zJ.jpg', 139, ARRAY['Drama'], ARRAY['Brad Pitt', 'Edward Norton', 'Helena Bonham Carter']),

('Spirited Away', 2001, 'Hayao Miyazaki', 'During her familys move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, where humans are changed into beasts.', 'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg', 'https://image.tmdb.org/t/p/original/6oaL4DP75yABrd5EbC4H2zq5ghc.jpg', 125, ARRAY['Animation', 'Adventure', 'Family'], ARRAY['Rumi Hiiragi', 'Miyu Irino', 'Mari Natsuki']),

('Whiplash', 2014, 'Damien Chazelle', 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a students potential.', 'https://image.tmdb.org/t/p/w500/oPxnRhyAIzJKGUEdSiwTJQBa3NM.jpg', 'https://image.tmdb.org/t/p/original/6bbZ6XyvgfjhQwbplnUh1LSj1ky.jpg', 106, ARRAY['Drama', 'Music'], ARRAY['Miles Teller', 'J.K. Simmons', 'Melissa Benoist']),

('The Prestige', 2006, 'Christopher Nolan', 'After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.', 'https://image.tmdb.org/t/p/w500/bdN3gXuIZYaJP7ftKK2sU0nPtEA.jpg', 'https://image.tmdb.org/t/p/original/c6SPLZ8cLsZlv62cXmxT5M3Nktv.jpg', 130, ARRAY['Drama', 'Mystery', 'Sci-Fi'], ARRAY['Christian Bale', 'Hugh Jackman', 'Scarlett Johansson']),

('Dune', 2021, 'Denis Villeneuve', 'A noble family becomes embroiled in a war for control over the galaxys most valuable asset while its heir becomes troubled by visions of a dark future.', 'https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg', 'https://image.tmdb.org/t/p/original/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg', 155, ARRAY['Action', 'Adventure', 'Sci-Fi'], ARRAY['Timothee Chalamet', 'Rebecca Ferguson', 'Zendaya']),

('The Social Network', 2010, 'David Fincher', 'As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by the twins who claimed he stole their idea.', 'https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg', 'https://image.tmdb.org/t/p/original/cqD03zyRcE8HYzUfTeFi35cz9pw.jpg', 120, ARRAY['Biography', 'Drama'], ARRAY['Jesse Eisenberg', 'Andrew Garfield', 'Justin Timberlake']),

('No Country for Old Men', 2007, 'Joel Coen', 'Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande.', 'https://image.tmdb.org/t/p/w500/bj1v6YKF8yHqA489VFfnQvOJpnc.jpg', 'https://image.tmdb.org/t/p/original/6d5XOczc226jECq0LIX0siKtgHR.jpg', 122, ARRAY['Crime', 'Drama', 'Thriller'], ARRAY['Tommy Lee Jones', 'Javier Bardem', 'Josh Brolin']),

('Blade Runner 2049', 2017, 'Denis Villeneuve', 'Young Blade Runner Ks discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, whos been missing for thirty years.', 'https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg', 'https://image.tmdb.org/t/p/original/sAtoMqDVhNDQBc3QJL3RF6hlhGq.jpg', 164, ARRAY['Action', 'Drama', 'Sci-Fi'], ARRAY['Ryan Gosling', 'Harrison Ford', 'Ana de Armas']),

('Everything Everywhere All at Once', 2022, 'Daniel Kwan', 'An aging Chinese immigrant is swept up in an insane adventure, where she alone can save the world by exploring other universes connecting with the lives she could have led.', 'https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg', 'https://image.tmdb.org/t/p/original/fL5pKiTfKLSAuRQY5b2XhWA7TxV.jpg', 139, ARRAY['Action', 'Adventure', 'Comedy'], ARRAY['Michelle Yeoh', 'Stephanie Hsu', 'Ke Huy Quan']);
